# Generated by Django 4.2.3 on 2023-07-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
