# Generated by Django 4.2.4 on 2023-08-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charities_organizations_name',
            fields=[
                ('charities_organizations_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(default='decription of organization', max_length=500)),
                ('contact_details', models.CharField(default='contact number', max_length=25)),
                ('email', models.EmailField(default='example@example.com', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='comments_and_feedback',
            fields=[
                ('comment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('user_ID', models.EmailField(default='example@example.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='donation_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ID', models.IntegerField()),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('donor_detaills', models.CharField(max_length=100, null=True)),
                ('organizations_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
