# Generated by Django 4.2.3 on 2023-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_user_table_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ID', models.IntegerField()),
            ],
        ),
    ]
