# Generated by Django 4.2.3 on 2023-07-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0004_donation_table_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_table',
            name='donor_detaills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation_table',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
