# Generated by Django 4.2.3 on 2023-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0005_donation_table_donor_detaills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='charities_organizations_name',
            fields=[
                ('charities_organizations_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='donation_table',
            name='organizations_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
