# Generated by Django 4.2.3 on 2023-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0006_charities_organizations_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charities_organizations_name',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
