# Generated by Django 4.2.3 on 2023-08-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0007_charities_organizations_name_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='charities_organizations_name',
            name='contact_details',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='charities_organizations_name',
            name='email',
            field=models.CharField(null=True),
        ),
    ]
