# Generated by Django 4.2.3 on 2023-08-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0009_alter_charities_organizations_name_contact_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments_and_feedback',
            fields=[
                ('comment_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
