# Generated by Django 4.2.3 on 2023-08-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0010_comments_and_feedback'),
    ]

    operations = [
        # commenting to fix error for removing id field
        
        # migrations.RemoveField(
        #     model_name='user_table',
        #     name='id',
        # ),
        migrations.AddField(
            model_name='comments_and_feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.user_table'),
        ),
        migrations.AlterField(
            model_name='charities_organizations_name',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, primary_key=True, serialize=False),
        ),
    ]
