# Generated by Django 4.2.3 on 2023-08-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0011_remove_user_table_id_comments_and_feedback_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_and_feedback',
            name='user',
        ),
    ]
