# Generated by Django 4.2.3 on 2023-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0012_remove_comments_and_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_and_feedback',
            name='user_ID',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
