# Generated by Django 4.2.3 on 2023-08-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0013_comments_and_feedback_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_and_feedback',
            name='user_ID',
        ),
    ]
