# Generated by Django 4.2.3 on 2023-08-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0016_alter_user_table_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
