# Generated by Django 4.2.3 on 2023-08-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0017_user_table_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_table',
        ),
    ]
