# Generated by Django 4.2.3 on 2023-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0018_delete_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
