# Generated by Django 4.2.3 on 2023-07-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_db_app', '0001_initial'),
    ]

    operations = [
         migrations.AddField(
             model_name='user_table',
             name='date_of_birth',
             field=models.DateField(default='DD-MM-YYYY'),
         ),
     ]
