# Generated by Django 4.2.3 on 2023-07-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_db_app', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_table',
        ),
    ]
